version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: TableTrack-PGDB
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: metiu123
      POSTGRES_DB: db_tabletrack_co
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    image: tabletrackapi:latest
    container_name: tabletrack_app
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/db_tabletrack_co
      DB_UNAME: postgres
      DB_PASS: metiu123
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres_data:
